services:
  postgres:
    image: postgres:18
    container_name: spring-ai-postgres
    environment:
      POSTGRES_DB: ai
      POSTGRES_USER: abopij
      POSTGRES_PASSWORD: hard-password
    ports:
      - "5432:5432"
    volumes:
      - postgres_spring_ai_data:/var/lib/postgresql
    restart: always

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped

    entrypoint: [ "/bin/sh", "-c" ]
    command: >
      "
      ollama serve &
      sleep 5;
      ollama pull gemma4:e2b;
      ollama pull mxbai-embed-large;
      wait
      "

  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - "7979:8080"
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
      WEBUI_SECRET_KEY: ""
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped


  chroma:
    image: chromadb/chroma:latest
    volumes:
      - chroma:/chroma/data
    ports:
      - "8000:8000"
    environment:
      - ALLOW_RESET=true
      - ANONYMIZED_TELEMETRY=false
    restart: unless-stopped


  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data


  ace-step:
    image: ghcr.io/dotnetautor/ace-step-1.5-docker:latest
    container_name: ace-step
    entrypoint: ["/bin/sh", "-lc"]
    command:
      - |
        set -e
        uv run acestep-download --list
        uv run acestep-download --dir /workspace/ace_music_platform/source_tree/checkpoints
        exec uv run acestep-api
    environment:
      PORT: "8001"
      SERVER_NAME: "0.0.0.0"
      LANGUAGE: "en"
      ACESTEP_DOWNLOAD_SOURCE: "huggingface"
      ACESTEP_INIT_LLM: "false"
      ACESTEP_OFFLOAD_TO_CPU: "true"
      ACESTEP_OFFLOAD_DIT_TO_CPU: "true"
      ACESTEP_VAE_ON_CPU: "1"
      ACESTEP_QUEUE_WORKERS: "1"
#      MAX_CUDA_VRAM: "12"
    ports:
      - "8001:8001"
    volumes:
      - ace-step-checkpoints:/workspace/ace_music_platform/source_tree/checkpoints
    restart: unless-stopped


volumes:
  postgres_spring_ai_data:
    driver: local
  ollama:
  open-webui:
  chroma:
  redis-data:
  ace-step-checkpoints:
